"""Bookmark definitions for the four rulebooks.

Entries are (level, title, printed_page).  Printed page numbers are taken
from each book's contents page; ``PAGE_OFFSET`` converts them to PDF pages.
Fleet Book entries whose title contains "Ship Designs" or "Merchant" get
per-ship child bookmarks detected automatically at build time.
"""

FULL_THRUST = [
    (1, "Cover", 0),
    (1, "Contents & Credits", 1),
    (1, "SECTION 1: INTRODUCTION", 2),
    (1, "SECTION 2: CORE RULES", 3),
    (2, "SHIP MODELS AND OTHER PLAYING PIECES", 3),
    (2, "DICE", 3),
    (2, "OTHER EQUIPMENT FOR PLAY", 3),
    (2, "PLAYING AREA", 3),
    (2, "UNITS OF DISTANCE", 3),
    (2, "SEQUENCE OF PLAY", 3),
    (2, "SHIP GROUPS AND CLASSES", 5),
    (2, "COURSE DETERMINATION", 5),
    (2, "SHIP VELOCITY", 5),
    (2, "THRUST RATINGS", 6),
    (2, "MOVEMENT", 6),
    (2, "MAKING COURSE CHANGES", 6),
    (2, "MOVEMENT ORDERS", 7),
    (2, "SPECIAL NOTES ON MOVEMENT", 7),
    (2, "FIRE CONTROL SYSTEMS", 7),
    (2, "FIRE ARCS", 8),
    (2, "BEAM WEAPON BATTERIES", 9),
    (2, "BEARING OF BEAM BATTERIES", 9),
    (2, "WEAPON RANGES, FIRING AND DAMAGE", 9),
    (2, "DEFENSIVE SCREENS", 10),
    (2, "'THRESHOLD POINTS' AND SPECIFIC SYSTEMS DAMAGE", 10),
    (2, "SHIPS LEAVING THE TABLE", 11),
    (2, "FILLING OUT THE SHIP RECORD SHEET", 12),
    (1, "INTRODUCTORY SCENARIO", 12),
    (2, "THE FIRST BATTLE OF GRENDEL, 2137", 12),
    (2, "SHIP RECORD SHEET EXAMPLE", 13),
    (1, "SECTION 3: SHIP CLASSES", 14),
    (2, "BASIC SHIP CLASSES AND HULL SIZES", 14),
    (2, "BASIC SHIP DIAGRAMS", 14),
    (2, "KEY TO SYMBOLS USED ON BASIC SHIP DESIGNS", 14),
    (1, "SECTION 4: ADVANCED RULES - FIGHTERS", 16),
    (2, "FIGHTERS", 16),
    (2, "FIGHTER ATTACKS", 16),
    (2, "ANTI-FIGHTER DEFENCES", 17),
    (2, "FIGHTER TO FIGHTER COMBAT", 17),
    (1, "SECTION 5: ADVANCED RULES - WEAPONS", 18),
    (2, "PULSE TORPEDOES", 18),
    (2, "NEEDLE BEAMS", 18),
    (2, "SUBMUNITION PACKS", 18),
    (2, "MINES", 18),
    (2, "MINELAYING", 18),
    (2, "MINESWEEPING", 19),
    (2, "SPINAL-MOUNT NOVA CANNON", 19),
    (1, "SECTION 6: ADVANCED RULES - GENERAL", 21),
    (2, "SENSORS AND TARGET IDENTIFICATION", 21),
    (2, "'DUMMY' BOGEYS AND 'WEASEL BOATS'", 22),
    (2, "COLLISION AND RAMMING", 22),
    (2, "MERCHANT SHIPS: DAMAGE TO CARGO AND HOLDS", 23),
    (2, "FASTER-THAN-LIGHT (FTL) DRIVES", 23),
    (2, "LEAVING THE TABLE UNDER FTL DRIVE", 23),
    (2, "ENTERING BATTLE UNDER FTL DRIVE", 24),
    (2, "ASTEROIDS", 25),
    (2, "MOVEMENT OF ASTEROIDS", 26),
    (2, "NON-FTL SHIPS", 26),
    (2, "FTL TUGS AND TENDERS", 27),
    (2, "STARBASES AND OTHER INSTALLATIONS", 27),
    (2, "3D, OR NOT 3D ...?", 28),
    (2, "'Q' SHIPS", 28),
    (1, "SECTION 7: ADVANCED SHIP DESIGN", 29),
    (2, "SHIP DESIGN AND POINTS COSTS", 29),
    (2, "'STANDARD' AND 'SPECIAL' HULLS", 29),
    (2, "HULL COST", 29),
    (2, "DRIVE SYSTEMS COST", 29),
    (2, "FITTING WEAPONS AND OTHER SYSTEMS", 30),
    (2, "SYMBOLS FOR WEAPONS FROM ADVANCED RULES", 30),
    (2, "MASS VALUES AND POINTS COSTS FOR WEAPONS AND SYSTEMS", 31),
    (1, "SECTION 8: BATTLE SCENARIOS", 32),
    (2, "SCENARIO A: THE ATTACK ON CONVOY 990", 32),
    (2, "SCENARIO B: MINING STATION CON-AM 12", 33),
    (1, "SECTION 9: CAMPAIGN RULES", 33),
    (2, "CAMPAIGN GAMES: INTRODUCTION", 33),
    (2, "THE CAMPAIGN MAP", 34),
    (2, "USE OF AN UMPIRE", 34),
    (2, "WHEN FLEETS MEET IN A STAR SYSTEM", 34),
    (2, "THE STAND OFF", 35),
    (2, "CAMPAIGN OBJECTIVES AND VICTORY CONDITIONS", 35),
    (2, "REPAIRS, REPLENISHMENT AND REINFORCEMENTS", 35),
    (1, "SECTION 10: CAMPAIGN SCENARIO", 36),
    (2, "THE LAFAYETTE INCIDENT, 2178", 36),
    (2, "CAMPAIGN SET-UP", 36),
    (2, "TIME SCALE AND VICTORY CONDITIONS", 36),
    (2, "POSSIBLE STRATEGIES", 36),
    (2, "THE FORCES", 36),
    (2, "CAMPAIGN SCENARIO MAP", 37),
    (2, "THE LAFAYETTE SECTOR", 38),
    (1, "SECTION 11: BACKGROUND", 40),
    (2, "THE BACKGROUND AND TIMELINE", 40),
    (2, "MAN'S ROAD TO THE STARS", 40),
    (2, "HUMAN HISTORY 1992 TO 2183", 42),
    (2, "SITUATION UPDATE: 2183", 43),
    (1, "SECTION 12: APPENDICES", 44),
    (2, "USING MINIATURES", 44),
    (2, "STARSHIP MODEL AVAILABILITY", 44),
    (2, "THE COUNTERS AND TEMPLATES", 45),
    (2, "COPELAND'S MODELS \"FULL THRUST\" MINIATURES", 46),
    (2, "SHIP COUNTERS AND COURSE GAUGE TEMPLATE", 47),
    (2, "SHIP RECORD SHEET", 48),
]

MORE_THRUST = [
    (1, "Contents & Credits", 1),
    (1, "SECTION 1: INTRODUCTION", 2),
    (2, "DESIGNER'S NOTES", 2),
    (2, "DESIGN CREDITS", 2),
    (2, "FULL THRUST ERRATA", 2),
    (1, "SECTION 2: NEW WEAPONS AND SYSTEMS", 3),
    (2, "MISSILES", 3),
    (2, "\"AA\" MEGABATTERIES", 3),
    (2, "WAVE GUN", 3),
    (2, "PLANETARY BOMBARDMENT SYSTEM (ORTILLERY)", 4),
    (2, "REFLEX FIELD", 4),
    (2, "CLOAKING FIELD", 4),
    (1, "SECTION 3: NEW OPTIONAL RULES", 5),
    (2, "BASIC RULES REVISIONS", 5),
    (2, "USING \"C\" BATTERIES AS ANTI-FIGHTER/ANTI-MISSILE WEAPONS", 5),
    (2, "SENSORS - EXPANDED RULES", 5),
    (2, "SENSOR JAMMING - ELECTRONIC COUNTER MEASURES", 6),
    (2, "DAMAGE CONTROL", 6),
    (2, "BOARDING ACTIONS", 7),
    (2, "FLEET MORALE", 8),
    (2, "STRIKING THE COLOURS", 8),
    (2, "SQUADRON OPERATIONS (LARGE FLEETS)", 8),
    (2, "\"TERRAIN\" EFFECTS", 9),
    (1, "SECTION 4: EXPANDED FIGHTER RULES", 10),
    (2, "OPTIONAL FIGHTER TURN SEQUENCE", 10),
    (2, "FIGHTER GROUP MORALE", 10),
    (2, "\"SCRAMBLING\" FIGHTER GROUPS", 11),
    (2, "FIGHTER ENDURANCE", 11),
    (2, "FIGHTER PILOT QUALITY: ACES AND TURKEYS", 11),
    (2, "ADVANCED AND SPECIALISED FIGHTER TYPES", 12),
    (1, "SECTION 5: PLANETS AND ATMOSPHERIC OPERATIONS", 13),
    (2, "PLANETS AND OTHER LARGE BODIES", 13),
    (2, "ENTERING AND LEAVING PLANETARY ORBIT", 13),
    (2, "ATMOSPHERIC STREAMLINING", 13),
    (2, "ATMOSPHERIC ENTRY - PLANNED AND ACCIDENTAL", 14),
    (1, "SECTION 6: COMBINING WITH GROUND COMBAT GAMES", 15),
    (2, "INTERFACING SPACE AND GROUND COMBAT ACTIONS", 15),
    (2, "FULL THRUST/DIRTSIDE II INTERFACE", 15),
    (2, "TRANSPORTING GROUND TROOPS", 15),
    (2, "INTERFACE CRAFT", 16),
    (2, "GROUND SUPPORT FOR DIRTSIDE II GAMES", 17),
    (2, "\"FULL THRUST\" FIGHTERS IN GROUND SUPPORT", 17),
    (2, "MARINE CONTINGENTS", 17),
    (2, "DAMAGE TO TROOP TRANSPORTS", 18),
    (2, "FULL THRUST/HELLFIRE INTERFACE", 19),
    (2, "GROUND SUPPORT IN \"HELLFIRE\"", 20),
    (2, "INTERFACING WITH OTHER SYSTEMS", 20),
    (1, "SECTION 7: COMPETITIVE AND TOURNAMENT GAMES", 21),
    (2, "SHIP DESIGN AND FLEET COMPOSITION", 21),
    (2, "SIZE OF FLEETS", 21),
    (2, "TYPE OF GAME AND SCENARIO", 21),
    (2, "SUGGESTED SPECIAL RULES AND LIMITATIONS", 21),
    (1, "SECTION 8: SHIP DESIGNS", 22),
    (2, "SUPERSHIPS", 22),
    (2, "EXPANDED SPACE INSTALLATION RULES", 22),
    (2, "NEW GENERAL DESIGNS", 22),
    (1, "SECTION 9: XENO FILE 1 - THE KRA'VAK", 24),
    (2, "CONTACT!", 24),
    (2, "OVERVIEW OF KRA'VAK TECHNOLOGY", 25),
    (2, "KRA'VAK THRUST AND MANOEUVRE", 25),
    (2, "KRA'VAK ARMOURED HULL COSTS", 25),
    (2, "BEAM WEAPON FIRE AGAINST KRA'VAK ARMOUR", 25),
    (2, "KRA'VAK RAILGUNS", 25),
    (2, "RAILGUN FIRE ARCS", 25),
    (2, "RAILGUNS AGAINST SCREENED TARGETS", 25),
    (2, "KRA'VAK \"SCATTERGUNS\"", 26),
    (2, "KRA'VAK FIGHTERS", 26),
    (2, "NOTES ON COMBINING HUMAN AND KRA'VAK TECHNOLOGIES", 26),
    (2, "MASS AND POINTS VALUES FOR KRA'VAK WEAPONRY AND SYSTEMS", 26),
    (2, "KRA'VAK BASIC SHIP DESIGNS", 27),
    (1, "SECTION 10: XENO FILE 2 - THE SA'VASKU", 28),
    (2, "THE SA'VASKU", 28),
    (2, "THE ROLE OF THE SA'VASKU", 29),
    (2, "SA'VASKU BIOSHIPS", 29),
    (2, "USING POWER POINTS", 30),
    (2, "ENERGY PULSE WEAPONS FIRE", 30),
    (2, "ANTI-FIGHTER FIRE", 30),
    (2, "DAMAGE POINTS", 30),
    (2, "SCREENS", 30),
    (2, "DRONE PODS", 30),
    (2, "FTL DRIVES", 31),
    (2, "SA'VASKU SHIP DIAGRAM", 31),
    (2, "USING SA'VASKU SHIPS", 31),
    (1, "SECTION 11: BACKGROUND", 32),
    (2, "TIMELINE CONTINUATION", 32),
    (2, "SCIENCE AND TECHNOLOGY IN FULL THRUST", 33),
    (2, "USING FULL THRUST IN OTHER BACKGROUNDS", 35),
    (2, "THE HUMOUR ELEMENT", 35),
    (1, "SECTION 12: SCENARIOS", 36),
    (2, "THE ASSAULT ON STARBASE 13", 36),
    (2, "LIBERTÉ", 37),
    (2, "THE BATTLE OF STIG IV", 37),
    (2, "SCENARIO OUTLINES", 39),
    (1, "SECTION 13: MODEL AVAILABILITY", 40),
    (2, "UPDATE OF AVAILABLE MODELS", 40),
    (2, "THE \"FULL THRUST\" STARSHIP RANGE", 40),
]

FLEET_BOOK_1 = [
    (1, "Contents & Credits", 1),
    (1, "Introduction and Designer's Notes", 2),
    (1, "Vector Movement System", 3),
    (1, "New Fire Arc Rules", 4),
    (1, "Rolling Ships", 5),
    (1, "Reroll and Damage Rules", 5),
    (1, "Core Systems Rules", 5),
    (1, "Expanded Fighter Rules", 6),
    (1, "Modified Weapons Systems", 6),
    (1, "Defensive and Other Systems", 7),
    (1, "Turn Sequence Summary", 8),
    (1, "Salvo Missile Systems", 9),
    (1, "Ship Design", 10),
    (1, "Mass and Points Cost Table", 11),
    (1, "Summary of Weapon Systems", 12),
    (1, "NAC Ship Designs", 13),
    (1, "NSL Ship Designs", 20),
    (1, "FSE Ship Designs", 27),
    (1, "ESU Ship Designs", 34),
    (1, "Merchant and Support Vessels", 42),
    (1, "Background Information", 43),
    (1, "Final Comments and Counters", 46),
    (1, "New Ship Record Sheet", 47),
    (1, "Full Thrust Starship Miniatures List", 48),
]

FLEET_BOOK_2 = [
    (1, "Contents & Credits", 1),
    (1, "Introduction", 2),
    (1, "Basic Ship Design", 3),
    (1, "Game Balance", 3),
    (1, "Combining Technologies", 3),
    (1, "Vector Movement Amendments", 3),
    (1, "Fighter Rules", 4),
    (1, "Core Systems", 4),
    (1, "Turn Sequence Summary", 5),
    (1, "Ship Data Panels", 6),
    (1, "Ship Record Charts", 6),
    (1, "Counters", 6),
    (1, "Xeno File 1: The Kra'Vak", 7),
    (2, "Kra'Vak Ship Design System", 9),
    (2, "Kra'Vak Systems Summary", 11),
    (2, "Kra'Vak Ship Designs", 12),
    (2, "Kra'Vak Ship Record Chart", 20),
    (1, "Xeno File 2: The Sa'Vasku", 21),
    (2, "Sa'Vasku Ship Design System", 21),
    (2, "Sa'Vasku Systems Summary", 25),
    (2, "Sa'Vasku Ship Designs", 26),
    (2, "Sa'Vasku Ship Record Chart", 33),
    (1, "Xeno File 3: The Phalons", 34),
    (2, "Phalon Ship Design System", 35),
    (2, "Phalon Ship Designs", 38),
    (2, "Phalon Systems Summary", 45),
    (2, "Phalon Ship Record Chart", 46),
    (1, "Background Timeline", 47),
    (1, "Full Thrust Starship Miniatures List", 48),
]
